@if defined __OROCOS_ROCK_CONDA_ACTIVE @goto orocos_activate_runtime

@set "__OROCOS_ROCK_OROCOS_PREFIX_SET=0"
@if defined OROCOS_PREFIX @set "__OROCOS_ROCK_OROCOS_PREFIX_SET=1"
@set "__OROCOS_ROCK_OROCOS_PREFIX_VALUE=%OROCOS_PREFIX%"
@set "__OROCOS_ROCK_OROCOS_TARGET_SET=0"
@if defined OROCOS_TARGET @set "__OROCOS_ROCK_OROCOS_TARGET_SET=1"
@set "__OROCOS_ROCK_OROCOS_TARGET_VALUE=%OROCOS_TARGET%"
@set "__OROCOS_ROCK_RTT_COMPONENT_PATH_SET=0"
@if defined RTT_COMPONENT_PATH @set "__OROCOS_ROCK_RTT_COMPONENT_PATH_SET=1"
@set "__OROCOS_ROCK_RTT_COMPONENT_PATH_VALUE=%RTT_COMPONENT_PATH%"
@set "__OROCOS_ROCK_PKG_CONFIG_LIBDIR_SET=0"
@if defined PKG_CONFIG_LIBDIR @set "__OROCOS_ROCK_PKG_CONFIG_LIBDIR_SET=1"
@set "__OROCOS_ROCK_PKG_CONFIG_LIBDIR_VALUE=%PKG_CONFIG_LIBDIR%"
@set "__OROCOS_ROCK_PKG_CONFIG_PATH_SET=0"
@if defined PKG_CONFIG_PATH @set "__OROCOS_ROCK_PKG_CONFIG_PATH_SET=1"
@set "__OROCOS_ROCK_PKG_CONFIG_PATH_VALUE=%PKG_CONFIG_PATH%"
@set "__OROCOS_ROCK_TYPELIB_PLUGIN_PATH_SET=0"
@if defined TYPELIB_PLUGIN_PATH @set "__OROCOS_ROCK_TYPELIB_PLUGIN_PATH_SET=1"
@set "__OROCOS_ROCK_TYPELIB_PLUGIN_PATH_VALUE=%TYPELIB_PLUGIN_PATH%"
@set "__OROCOS_ROCK_CMAKE_PREFIX_PATH_SET=0"
@if defined CMAKE_PREFIX_PATH @set "__OROCOS_ROCK_CMAKE_PREFIX_PATH_SET=1"
@set "__OROCOS_ROCK_CMAKE_PREFIX_PATH_VALUE=%CMAKE_PREFIX_PATH%"
@set "__OROCOS_ROCK_PATH_RUNTIME_PLUGIN_PRESENT=1"
@set "__OROCOS_ROCK_RECORD_RUNTIME_PLUGIN=1"
@set "__OROCOS_ROCK_CONDA_ACTIVE=1"

:orocos_activate_runtime
@call "%~dp0..\..\..\Library\env.bat" --conda
@call :orocos_activate_return %ERRORLEVEL%
@exit /b %ERRORLEVEL%

:orocos_activate_return
@set "__OROCOS_ROCK_RECORD_RUNTIME_PLUGIN="
@if "%~1"=="0" @exit /b 0
@call "%~dp0..\deactivate.d\orocos-deactivate.bat"
@exit /b %~1
