#!/bin/sh

if [ -z "${CONDA_PREFIX:-}" ]; then
    printf '%s\n' 'Cannot activate Orocos runtime: CONDA_PREFIX is not set.' >&2
    return 1
fi

if [ ! -f "$CONDA_PREFIX/env.sh" ]; then
    printf 'Cannot activate Orocos runtime: missing %s.\n' \
        "$CONDA_PREFIX/env.sh" >&2
    return 1
fi

if [ "${__OROCOS_ROCK_CONDA_ACTIVE:-}" != "1" ]; then
    __OROCOS_ROCK_OROCOS_PREFIX_SET=${OROCOS_PREFIX+x}
    __OROCOS_ROCK_OROCOS_PREFIX_VALUE=${OROCOS_PREFIX-}
    __OROCOS_ROCK_OROCOS_TARGET_SET=${OROCOS_TARGET+x}
    __OROCOS_ROCK_OROCOS_TARGET_VALUE=${OROCOS_TARGET-}
    __OROCOS_ROCK_LD_LIBRARY_PATH_SET=${LD_LIBRARY_PATH+x}
    __OROCOS_ROCK_LD_LIBRARY_PATH_VALUE=${LD_LIBRARY_PATH-}
    __OROCOS_ROCK_CMAKE_PREFIX_PATH_SET=${CMAKE_PREFIX_PATH+x}
    __OROCOS_ROCK_CMAKE_PREFIX_PATH_VALUE=${CMAKE_PREFIX_PATH-}
    __OROCOS_ROCK_PKG_CONFIG_PATH_SET=${PKG_CONFIG_PATH+x}
    __OROCOS_ROCK_PKG_CONFIG_PATH_VALUE=${PKG_CONFIG_PATH-}
    __OROCOS_ROCK_RTT_COMPONENT_PATH_SET=${RTT_COMPONENT_PATH+x}
    __OROCOS_ROCK_RTT_COMPONENT_PATH_VALUE=${RTT_COMPONENT_PATH-}
    __OROCOS_ROCK_TYPELIB_PLUGIN_PATH_SET=${TYPELIB_PLUGIN_PATH+x}
    __OROCOS_ROCK_TYPELIB_PLUGIN_PATH_VALUE=${TYPELIB_PLUGIN_PATH-}

    case ":${PATH-}:" in
        *:"$CONDA_PREFIX/bin":*)
            __OROCOS_ROCK_PATH_PREFIX_BIN_PRESENT=1
            ;;
        *)
            __OROCOS_ROCK_PATH_PREFIX_BIN_PRESENT=0
            ;;
    esac
    case ":${PATH-}:" in
        *:"$CONDA_PREFIX/toolchain/bin":*)
            __OROCOS_ROCK_PATH_TOOLCHAIN_BIN_PRESENT=1
            ;;
        *)
            __OROCOS_ROCK_PATH_TOOLCHAIN_BIN_PRESENT=0
            ;;
    esac

    __OROCOS_ROCK_ACTIVATION_PREFIX=$CONDA_PREFIX
    __OROCOS_ROCK_CONDA_ACTIVE=1
    export __OROCOS_ROCK_OROCOS_PREFIX_SET
    export __OROCOS_ROCK_OROCOS_PREFIX_VALUE
    export __OROCOS_ROCK_OROCOS_TARGET_SET
    export __OROCOS_ROCK_OROCOS_TARGET_VALUE
    export __OROCOS_ROCK_LD_LIBRARY_PATH_SET
    export __OROCOS_ROCK_LD_LIBRARY_PATH_VALUE
    export __OROCOS_ROCK_CMAKE_PREFIX_PATH_SET
    export __OROCOS_ROCK_CMAKE_PREFIX_PATH_VALUE
    export __OROCOS_ROCK_PKG_CONFIG_PATH_SET
    export __OROCOS_ROCK_PKG_CONFIG_PATH_VALUE
    export __OROCOS_ROCK_RTT_COMPONENT_PATH_SET
    export __OROCOS_ROCK_RTT_COMPONENT_PATH_VALUE
    export __OROCOS_ROCK_TYPELIB_PLUGIN_PATH_SET
    export __OROCOS_ROCK_TYPELIB_PLUGIN_PATH_VALUE
    export __OROCOS_ROCK_PATH_PREFIX_BIN_PRESENT
    export __OROCOS_ROCK_PATH_TOOLCHAIN_BIN_PRESENT
    export __OROCOS_ROCK_ACTIVATION_PREFIX
    export __OROCOS_ROCK_CONDA_ACTIVE
fi

# shellcheck disable=SC1091
. "$CONDA_PREFIX/env.sh"
