#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
. "$SCRIPT_DIR/common.sh"

usage() {
    cat <<'USAGE'
Usage: ./tools/export-env.sh [--prefix PREFIX] [--target gnulinux|xenomai]

Write PREFIX/env.sh and PREFIX/dev-env.sh for consuming an installed
Orocos/Rock toolchain prefix.

Options:
  --prefix PREFIX  Installed toolchain prefix. Default: $OROCOS_PREFIX or ~/.orocos
  --target TARGET  Orocos target exported by env.sh. Default: $OROCOS_TARGET or gnulinux
  -h, --help       Show this help
USAGE
}

PREFIX="$OROCOS_ROCK_DEFAULT_PREFIX"
TARGET="$OROCOS_ROCK_DEFAULT_TARGET"

while [ "$#" -gt 0 ]; do
    case "$1" in
        --prefix)
            [ "$#" -ge 2 ] || orocos_rock_die "--prefix requires a value"
            PREFIX="$2"
            shift 2
            ;;
        --target)
            [ "$#" -ge 2 ] || orocos_rock_die "--target requires a value"
            TARGET="$2"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            usage >&2
            orocos_rock_die "unknown argument: $1"
            ;;
    esac
done

orocos_rock_validate_target "$TARGET"

mkdir -p "$PREFIX"
PREFIX="$(cd "$PREFIX" && pwd)"
RUBY_VERSION_ABI="$(ruby -rrbconfig -e 'print RbConfig::CONFIG.fetch("ruby_version")')"
RUBY_ARCH="$(ruby -rrbconfig -e 'print RbConfig::CONFIG.fetch("arch")')"

cat >"$PREFIX/env.sh" <<EOF
#!/usr/bin/env sh
# Generated by orocos-rock/tools/export-env.sh.

OROCOS_PREFIX="$PREFIX"
export OROCOS_PREFIX

orocos_rock_prepend_path() {
    name="\$1"
    value="\$2"
    [ -d "\$value" ] || return 0
    eval "current=\\\${\$name:-}"
    case ":\$current:" in
        *:"\$value":*) ;;
        *)
            if [ -n "\$current" ]; then
                eval "export \$name=\"\$value:\$current\""
            else
                eval "export \$name=\"\$value\""
            fi
            ;;
    esac
}

orocos_rock_multiarch="\$(uname -m)-linux-gnu"

orocos_rock_prepend_path PATH "\$OROCOS_PREFIX/bin"
orocos_rock_prepend_path PATH "\$OROCOS_PREFIX/toolchain/bin"
orocos_rock_prepend_path LD_LIBRARY_PATH "\$OROCOS_PREFIX/lib"
orocos_rock_prepend_path LD_LIBRARY_PATH "\$OROCOS_PREFIX/lib64"
orocos_rock_prepend_path LD_LIBRARY_PATH "\$OROCOS_PREFIX/lib/\$orocos_rock_multiarch"
orocos_rock_prepend_path LD_LIBRARY_PATH "\$OROCOS_PREFIX/toolchain/lib"
orocos_rock_prepend_path LD_LIBRARY_PATH "\$OROCOS_PREFIX/toolchain/lib64"
orocos_rock_prepend_path LD_LIBRARY_PATH "\$OROCOS_PREFIX/toolchain/lib/\$orocos_rock_multiarch"
orocos_rock_prepend_path CMAKE_PREFIX_PATH "\$OROCOS_PREFIX"
orocos_rock_prepend_path CMAKE_PREFIX_PATH "\$OROCOS_PREFIX/toolchain"
orocos_rock_prepend_path PKG_CONFIG_PATH "\$OROCOS_PREFIX/lib/pkgconfig"
orocos_rock_prepend_path PKG_CONFIG_PATH "\$OROCOS_PREFIX/lib64/pkgconfig"
orocos_rock_prepend_path PKG_CONFIG_PATH "\$OROCOS_PREFIX/lib/\$orocos_rock_multiarch/pkgconfig"
orocos_rock_prepend_path PKG_CONFIG_PATH "\$OROCOS_PREFIX/share/pkgconfig"
orocos_rock_prepend_path PKG_CONFIG_PATH "\$OROCOS_PREFIX/toolchain/lib/pkgconfig"
orocos_rock_prepend_path PKG_CONFIG_PATH "\$OROCOS_PREFIX/toolchain/lib64/pkgconfig"
orocos_rock_prepend_path PKG_CONFIG_PATH "\$OROCOS_PREFIX/toolchain/lib/\$orocos_rock_multiarch/pkgconfig"
orocos_rock_prepend_path PKG_CONFIG_PATH "\$OROCOS_PREFIX/toolchain/share/pkgconfig"
orocos_rock_prepend_path RTT_COMPONENT_PATH "\$OROCOS_PREFIX/lib/orocos"
orocos_rock_prepend_path RTT_COMPONENT_PATH "\$OROCOS_PREFIX/lib/orocos/plugins"
orocos_rock_prepend_path RTT_COMPONENT_PATH "\$OROCOS_PREFIX/lib64/orocos"
orocos_rock_prepend_path RTT_COMPONENT_PATH "\$OROCOS_PREFIX/lib64/orocos/plugins"
orocos_rock_prepend_path RTT_COMPONENT_PATH "\$OROCOS_PREFIX/toolchain/lib/orocos"
orocos_rock_prepend_path RTT_COMPONENT_PATH "\$OROCOS_PREFIX/toolchain/lib/orocos/plugins"
orocos_rock_prepend_path RTT_COMPONENT_PATH "\$OROCOS_PREFIX/toolchain/lib64/orocos"
orocos_rock_prepend_path RTT_COMPONENT_PATH "\$OROCOS_PREFIX/toolchain/lib64/orocos/plugins"
orocos_rock_prepend_path TYPELIB_PLUGIN_PATH "\$OROCOS_PREFIX/toolchain/lib/typelib"

OROCOS_TARGET="$TARGET"
export OROCOS_TARGET

if [ "\$OROCOS_TARGET" = "xenomai" ]; then
    XENOMAI_DIR="\${XENOMAI_DIR:-${XENOMAI_DIR:-$OROCOS_ROCK_DEFAULT_XENOMAI_DIR}}"
    XENOMAI_ROOT_DIR="\${XENOMAI_ROOT_DIR:-\$XENOMAI_DIR}"
    export XENOMAI_DIR
    export XENOMAI_ROOT_DIR
    orocos_rock_prepend_path PATH "\$XENOMAI_DIR/bin"
fi

unset orocos_rock_multiarch
unset -f orocos_rock_prepend_path
EOF

cat >"$PREFIX/dev-env.sh" <<EOF
#!/usr/bin/env sh
# Generated by orocos-rock/tools/export-env.sh.

# shellcheck disable=SC1091
. "$PREFIX/env.sh"

GEM_HOME="\$OROCOS_PREFIX/toolchain/gems"
export GEM_HOME

orocos_rock_default_gem_dir="\$(ruby -rrubygems -e 'print Gem.default_dir')"
GEM_PATH="\$GEM_HOME:\$orocos_rock_default_gem_dir"
export GEM_PATH

orocos_rock_prepend_path() {
    name="\$1"
    value="\$2"
    [ -d "\$value" ] || return 0
    eval "current=\\\${\$name:-}"
    case ":\$current:" in
        *:"\$value":*) ;;
        *)
            if [ -n "\$current" ]; then
                eval "export \$name=\"\$value:\$current\""
            else
                eval "export \$name=\"\$value\""
            fi
            ;;
    esac
}

orocos_rock_prepend_path RUBYLIB "\$OROCOS_PREFIX/toolchain/lib/ruby/$RUBY_VERSION_ABI"
orocos_rock_prepend_path RUBYLIB "\$OROCOS_PREFIX/toolchain/lib/$RUBY_ARCH/ruby/$RUBY_VERSION_ABI"
orocos_rock_prepend_path RUBYLIB "\$OROCOS_PREFIX/toolchain/lib/ruby/$RUBY_VERSION_ABI/$RUBY_ARCH"
unset orocos_rock_default_gem_dir
unset -f orocos_rock_prepend_path
EOF

chmod +x "$PREFIX/env.sh" "$PREFIX/dev-env.sh"

orocos_rock_info "Wrote $PREFIX/env.sh"
orocos_rock_info "Wrote $PREFIX/dev-env.sh"
